version: '3.8'

services:
  frontend:
    # Use context 'frontend' so Dockerfile paths work correctly
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: academic-frontend
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      # Backend URL for server-side proxying (internal Docker DNS)
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: academic-backend
    restart: unless-stopped
    ports:
      - "8099:8000"
    volumes:
      - academic_pdf_data:/app/data/pdfs
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/academic_db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: academic-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=academic_db
    volumes:
      - academic_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d academic_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  academic_postgres_data:
  academic_pdf_data:
